[Service]
EnvironmentFile=/etc/ndsp/ndsp-db.env
Environment="DATABASE_URL=postgresql://<REDACTED_CREDENTIALS>@127.0.0.1:5432/ndsp_auth"
Environment="POSTGRES_URL=postgresql://<REDACTED_CREDENTIALS>@127.0.0.1:5432/ndsp_auth"
Environment="PGHOST=127.0.0.1"
Environment="PGPORT=5432"
Environment="PGDATABASE=ndsp_auth"
Environment="PGUSER=ndsp_auth"
Environment="PGPASSWORD=d75089ca7527c0e97664fbd53f5628b781f16084b01d351e"
Environment="DB_HOST=127.0.0.1"
Environment="DB_PORT=5432"
Environment="DB_NAME=ndsp_auth"
Environment="DB_DATABASE=ndsp_auth"
Environment="DB_USER=ndsp_auth"
Environment="DB_USERNAME=ndsp_auth"
Environment="DB_PASSWORD=d75089ca7527c0e97664fbd53f5628b781f16084b01d351e"
Environment="POSTGRES_HOST=127.0.0.1"
Environment="POSTGRES_PORT=5432"
Environment="POSTGRES_DB=ndsp_auth"
Environment="POSTGRES_DATABASE=ndsp_auth"
Environment="POSTGRES_USER=ndsp_auth"
Environment="POSTGRES_PASSWORD=d75089ca7527c0e97664fbd53f5628b781f16084b01d351e"
