'use strict';

const { createNDSPService } = require('../../framework');

const service = createNDSPService({
  serviceId: '__SERVICE_ID__',
  serviceName: '__SERVICE_NAME__',
  product: '__PRODUCT__',
  domain: '__DOMAIN__',
  version: '__VERSION__',
  release: '__RELEASE__',
  owner: 'NDSP Engineering',
  component: '__SERVICE_ID__',
  description: '__SERVICE_NAME__ service generated by DEV-001 NDSP Developer Toolkit.',
  serviceRoot: __dirname,
  routes(app, { ctx }) {
    app.get('/service-info', (_req, res) => {
      res.json({
        ok: true,
        service: ctx.serviceId,
        service_name: ctx.serviceName,
        product: ctx.product,
        domain: ctx.domain,
        version: ctx.version,
        release: ctx.release,
        framework: 'ENG-001',
        generated_by: 'DEV-001',
        status: 'ACTIVE',
        timestamp: new Date().toISOString()
      });
    });
  }
});

service.start();
