# __SERVICE_ID__ — __SERVICE_NAME__

Generated by DEV-001 NDSP Developer Toolkit.

## Product

__PRODUCT__

## Domain

__DOMAIN__

## Port

127.0.0.1:__PORT__

## Endpoints

- GET /health
- GET /version
- GET /about
- GET /service-info

## Framework

Uses ENG-001 NDSP Service Framework.
