export default {
  nav: { home: "Beranda", plans: "Paket", trial: "Uji Coba", faq: "FAQ", login: "Masuk", register: "Daftar" },
  hero: { badge: "NDSP Elite Trial • Uji Coba Institusional Terbatas", title: "NDSP — Platform Dukungan Keputusan Institusional", subtitle: "Pahami konteks pasar • Evaluasi skenario • Buat keputusan lebih informatif", disclaimer: "Bukan rekomendasi trading — alat analisis edukasi yang dikelola", description: "Platform dukungan keputusan yang aman yang tidak memberikan rekomendasi keuangan langsung, tetapi menyajikan konteks analitis, status risiko, kualitas keputusan, dan wawasan terorganisir.", startTrial: "Mulai Uji Coba", viewJourney: "Lihat Perjalanan 16 Hari" },
  warning: { text: "Peringatan: NDSP adalah platform dukungan keputusan dan analisis kontekstual. Tidak memberikan rekomendasi keuangan, tidak mengeksekusi perintah, dan tidak mengelola modal pengguna." },
  status: { title: "Status Platform", visitor: "Pengunjung", visitorDesc: "Daftar untuk memulai uji coba 16 hari Anda.", backend: "Terhubung via /api", backendDesc: "Pendaftaran, login, dan survei terhubung ke PostgreSQL.", contact: "ndsp.app@gmail.com", contactDesc: "Email resmi untuk pertanyaan dan dukungan." },
  welcome: { title: "Pesan Selamat Datang", text: "Demi kepuasan Anda dan untuk memberi Anda kesempatan yang adil untuk merasakan kekuatan sistem, kami menawarkan uji coba perkenalan 16 hari untuk mengenal NDSP secara bertahap sebelum komitmen apapun.", startTrial: "Mulai Uji Coba", viewJourney: "Lihat Perjalanan 16 Hari" },
  seats: { title: "Kursi Uji Coba NDSP Terbatas", subtitle: "Kursi uji coba telah dibagi untuk memastikan kualitas evaluasi dan keragaman umpan balik sebelum peluncuran berbayar.", specialist: "Spesialis / Akademisi", specialistDesc: "Dialokasikan untuk pengulas berpengalaman, spesialis, dan mereka yang tertarik dengan evaluasi sistematis.", regular: "Pengguna Biasa / Pemula", regularDesc: "Dialokasikan untuk menguji kejelasan pengalaman bagi pengguna baru dan non-spesialis.", special: "Khusus / Premium", specialDesc: "Dialokasikan untuk pengguna unggul atau dengan penggunaan tingkat lanjut dan umpan balik kualitatif.", total: "Total kursi uji coba: 50 kursi" },
  plans: {
    title: "Paket dan Fitur", selectPlan: "Pilih Paket", locked: "Paket ini dikunci selama fase uji coba saat ini.", lockedSub: "Tombol pilih dan bayar akan diaktifkan setelah periode uji coba resmi berakhir.", features: "Fitur", hidden: "Disembunyikan di paket ini",
    insight: { name: "Insight", price: "Gratis", desc: "Untuk pengguna baru yang ingin mencoba sistem dan memahami konsep umum.", features: ["Tampilan umum status pasar", "Perjalanan 16 hari", "Survei hari ke-16", "FAQ, keamanan, dan privasi", "Pemberitahuan hukum yang jelas"], hidden: ["TDL terperinci", "Meeting point terperinci", "Meeting point The golden signal", "Black Layer", "API / Webhooks", "Panel admin"] },
    nmpPro: { name: "Meeting point Pro", price: "$49", desc: "Untuk pengguna serius yang menginginkan pemahaman lebih dalam tentang konteks, likuiditas, dan keselarasan.", features: ["TDL — Logika Dimensi Temporal", "Meeting point — Titik Pertemuan Nawaf", "Meeting point The golden signal", "Laporan interpretatif yang lebih jelas", "Tingkat risiko dan konteks lebih luas", "Uji coba 16 hari penuh"], hidden: ["Black Layer penuh", "Lima lapisan berdaulat yang dilindungi", "API / Webhooks", "Izin admin", "Logika mentah"] },
    elite16: { name: "Elite 16", price: "$149", desc: "Untuk pengguna tingkat lanjut yang menginginkan pengalaman analitis terluas dalam sistem.", features: ["Akses lebih luas ke logika 16 lapisan", "Black Layer — Advokat Iblis", "Kemampuan penjelasan yang diperluas", "Analisis risiko lanjutan dan konteks", "Prioritas pada diskon dan penawaran", "Prioritas pada pembaruan sistem"], hidden: ["Lima lapisan berdaulat dilindungi di UI", "Logika mentah", "Izin admin", "Kunci API institusional"] },
    saas: { name: "NDSP SaaS", price: "Kustom", desc: "Untuk perusahaan dan entitas yang perlu mengintegrasikan NDSP ke dalam sistem mereka.", features: ["Kunci API institusional", "Webhooks untuk sinyal umum yang bersih", "Batas kecepatan khusus", "Log audit", "Integrasi dengan sistem internal", "Dukungan teknis dan tinjauan operasional"], hidden: ["Algoritma mentah", "Lapisan yang sepenuhnya dilindungi", "Rahasia pembobotan internal", "Izin pemilik sistem"] },
  },
  trial: { badge: "NDSP Elite Trial • Uji Coba Institusional Terbatas", title: "Selamat Datang di Uji Coba NDSP 16 Hari", subtitle: "Fase ini didedikasikan untuk menguji platform sebelum peluncuran berbayar.", duration: "Durasi Uji Coba", durationVal: "16 hari sejak tanggal aktivasi akun uji coba.", currentPlan: "Paket Saat Ini", currentPlanVal: "Trial Plan — akses uji coba terorganisir sebelum peluncuran berbayar.", benefits: "Manfaat Uji Coba", benefitsVal: "Akses dasar, aset yang ditentukan, dan keluaran yang disederhanakan tanpa mengungkapkan logika internal.", survey: "Survei Akhir Periode", surveyVal: "Survei diperlukan untuk mengevaluasi pengalaman dan meningkatkan platform sebelum ekspansi.", limitedSeats: "Kursi Terbatas", limitedSeatsVal: "Kursi uji coba terbatas dan tunduk pada tinjauan dan aktivasi administratif.", payment: "Pembayaran Saat Ini", paymentVal: "Pembayaran sementara dikunci sampai fase uji coba selesai.", start: "Mengerti, Mulai Uji Coba", close: "Tutup" },
  about: { title: "Apa itu NDSP? Dan apa yang tidak ditawarkannya?", subtitle: "Platform ini dirancang untuk mengklarifikasi batasan layanan sebelum memulai uji coba.", whatIs: "Apa itu NDSP?", whatIsItems: ["Platform dukungan keputusan dan analisis kontekstual untuk pasar.", "Membantu memahami konteks dan mengevaluasi skenario.", "Menyajikan keluaran analitis yang dikelola dan disederhanakan.", "Mendukung uji coba Elite 16 hari sebelum peluncuran berbayar."], whatNot: "Apa yang TIDAK ditawarkan NDSP?", whatNotItems: ["Bukan penasihat keuangan.", "Tidak memberikan rekomendasi beli atau jual.", "Tidak mengeksekusi transaksi atau mengelola modal.", "Tidak menjamin hasil atau akurasi skenario masa depan."] },
  footer: { disclaimer: "Peringatan: NDSP adalah platform dukungan keputusan dan analisis kontekstual. Tidak memberikan rekomendasi keuangan, tidak mengeksekusi perintah, dan tidak mengelola modal pengguna.", rights: "Semua hak dilindungi" },
  languageSwitcher: { label: "Bahasa", search: "Cari bahasa...", noResults: "Tidak ada hasil" },
};
