export default {
  nav: { home: "Home", plans: "Plannen", trial: "Proefperiode", faq: "FAQ", login: "Inloggen", register: "Registreren" },
  hero: { badge: "NDSP Elite Trial • Beperkte institutionele proef", title: "NDSP — Institutioneel beslissingsondersteuningsplatform", subtitle: "Begrijp de marktcontext • Evalueer scenario's • Neem meer geïnformeerde beslissingen", disclaimer: "Geen handelsaanbevelingen — een bestuurd educatief analysetool", description: "Een veilig beslissingsondersteuningsplatform dat geen directe financiële aanbevelingen geeft, maar analytische context, risicostatus, beslissingsqualiteit en georganiseerd inzicht presenteert.", startTrial: "Proef starten", viewJourney: "16-dagenreis bekijken" },
  warning: { text: "Waarschuwing: NDSP is een platform voor beslissingsondersteuning en contextuele analyse. Het geeft geen financieel advies, voert geen orders uit en beheert geen gebruikerskapitaal." },
  status: { title: "Platformstatus", visitor: "Bezoeker", visitorDesc: "Registreer u om uw proefperiode van 16 dagen te starten.", backend: "Verbonden via /api", backendDesc: "Registratie, inloggen en enquête zijn verbonden met PostgreSQL.", contact: "ndsp.app@gmail.com", contactDesc: "Officieel e-mailadres voor vragen en ondersteuning." },
  welcome: { title: "Welkomstbericht", text: "Vanwege onze toewijding aan uw tevredenheid en om u een eerlijke kans te geven de kracht van het systeem te ervaren, bieden we u een introductieve proef van 16 dagen om NDSP geleidelijk te leren kennen voordat u enige verplichting aangaat.", startTrial: "Proef starten", viewJourney: "16-dagenreis bekijken" },
  seats: { title: "Beperkte NDSP-proefplaatsen", subtitle: "Proefplaatsen zijn verdeeld om de kwaliteit van de evaluatie en diversiteit van feedback te garanderen voor de betaalde lancering.", specialist: "Specialist / Academisch", specialistDesc: "Toegewezen aan ervaren beoordelaars, specialisten en geïnteresseerden in systematische evaluatie.", regular: "Gewone gebruiker / Beginner", regularDesc: "Toegewezen voor het testen van de helderheid van de ervaring voor nieuwe en niet-gespecialiseerde gebruikers.", special: "Speciaal / Premium", specialDesc: "Toegewezen voor onderscheiden gebruikers of met geavanceerd gebruik en kwalitatieve feedback.", total: "Totaal proefplaatsen: 50 plaatsen" },
  plans: {
    title: "Plannen en functies", selectPlan: "Plan kiezen", locked: "Dit plan is vergrendeld tijdens de huidige proeffase.", lockedSub: "Selectie- en betalingsknoppen worden geactiveerd na het einde van de officiële proefperiode.", features: "Functies", hidden: "Verborgen in dit plan",
    insight: { name: "Insight", price: "Gratis", desc: "Voor nieuwe gebruikers die het systeem willen ervaren en het algemene concept willen begrijpen.", features: ["Algemeen overzicht marktstatus", "16-dagenreis", "Dag 16 enquête", "FAQ, veiligheid en privacy", "Duidelijke juridische kennisgeving"], hidden: ["Gedetailleerde TDL", "Gedetailleerde Meeting point", "Meeting point The golden signal", "Black Layer", "API / Webhooks", "Beheerspaneel"] },
    nmpPro: { name: "Meeting point Pro", price: "$49", desc: "Voor serieuze gebruikers die een dieper inzicht willen in context, liquiditeit en afstemming.", features: ["TDL — Temporele dimensielogica", "Meeting point — Nawaf-ontmoetingspunt", "Meeting point The golden signal", "Duidelijkere interpretatieve rapporten", "Risiconiveaus en bredere context", "Volledige proef van 16 dagen"], hidden: ["Volledige Black Layer", "Vijf beschermde soevereine lagen", "API / Webhooks", "Beheerdersrechten", "Ruwe logica"] },
    elite16: { name: "Elite 16", price: "$149", desc: "Voor geavanceerde gebruikers die de breedste analytische ervaring binnen het systeem willen.", features: ["Bredere toegang tot 16-lagenlogica", "Black Layer — Advocaat van de duivel", "Uitgebreide uitlegbaarheid", "Geavanceerde risicoanalyse en context", "Prioriteit bij kortingen en aanbiedingen", "Prioriteit bij systeemupdates"], hidden: ["Vijf soevereine lagen beschermd in UI", "Ruwe logica", "Beheerdersrechten", "Institutionele API-sleutels"] },
    saas: { name: "NDSP SaaS", price: "Aangepast", desc: "Voor bedrijven en entiteiten die NDSP in hun systemen moeten integreren.", features: ["Institutionele API-sleutels", "Webhooks voor schone algemene signalen", "Aangepaste snelheidslimieten", "Auditlogboeken", "Integratie met interne systemen", "Technische ondersteuning en operationele beoordeling"], hidden: ["Ruwe algoritmen", "Volledig beschermde lagen", "Interne weginggeheimen", "Eigenaarsmachtigingen systeem"] },
  },
  trial: { badge: "NDSP Elite Trial • Beperkte institutionele proef", title: "Welkom bij de NDSP-proef van 16 dagen", subtitle: "Deze fase is gewijd aan het testen van het platform vóór de betaalde lancering.", duration: "Profduur", durationVal: "16 dagen vanaf de datum van activering van het proefaccount.", currentPlan: "Huidig plan", currentPlanVal: "Trial Plan — georganiseerde proeftoegang vóór de betaalde lancering.", benefits: "Proefvoordelen", benefitsVal: "Basistoegang, gedefinieerde activa en vereenvoudigde uitvoer zonder de interne logica te onthullen.", survey: "Enquête einde periode", surveyVal: "Enquête vereist om de ervaring te evalueren en het platform te verbeteren vóór uitbreiding.", limitedSeats: "Beperkte plaatsen", limitedSeatsVal: "Proefplaatsen zijn beperkt en onderworpen aan beoordeling en administratieve activering.", payment: "Huidige betaling", paymentVal: "Betaling is tijdelijk vergrendeld totdat de proeffase is voltooid.", start: "Begrepen, proef starten", close: "Sluiten" },
  about: { title: "Wat is NDSP? En wat biedt het niet?", subtitle: "Dit platform is ontworpen om de servicegrenzen te verduidelijken voordat de proef begint.", whatIs: "Wat is NDSP?", whatIsItems: ["Een platform voor beslissingsondersteuning en contextuele analyse voor markten.", "Helpt bij het begrijpen van context en het evalueren van scenario's.", "Presenteert bestuurde en vereenvoudigde analytische uitvoer.", "Ondersteunt de Elite proef van 16 dagen vóór de betaalde lancering."], whatNot: "Wat biedt NDSP NIET?", whatNotItems: ["Geen financieel adviseur.", "Geeft geen koop- of verkoopadvies.", "Voert geen transacties uit of beheert geen kapitaal.", "Garandeert geen resultaten of nauwkeurigheid van toekomstige scenario's."] },
  footer: { disclaimer: "Waarschuwing: NDSP is een platform voor beslissingsondersteuning en contextuele analyse. Het geeft geen financieel advies, voert geen orders uit en beheert geen gebruikerskapitaal.", rights: "Alle rechten voorbehouden" },
  languageSwitcher: { label: "Taal", search: "Taal zoeken...", noResults: "Geen resultaten" },
};
