export default {
  nav: { home: "Strona główna", plans: "Plany", trial: "Wersja próbna", faq: "FAQ", login: "Zaloguj się", register: "Zarejestruj się" },
  hero: { badge: "NDSP Elite Trial • Ograniczona wersja próbna dla instytucji", title: "NDSP — Instytucjonalna platforma wsparcia decyzji", subtitle: "Rozumiej kontekst rynkowy • Oceniaj scenariusze • Podejmuj bardziej świadome decyzje", disclaimer: "Nie są to rekomendacje handlowe — zarządzane edukacyjne narzędzie analityczne", description: "Bezpieczna platforma wsparcia decyzji, która nie udziela bezpośrednich rekomendacji finansowych, lecz przedstawia kontekst analityczny, stan ryzyka, jakość decyzji i zorganizowane spostrzeżenia.", startTrial: "Rozpocznij próbę", viewJourney: "Zobacz 16-dniową podróż" },
  warning: { text: "Ostrzeżenie: NDSP to platforma wsparcia decyzji i analizy kontekstowej. Nie udziela porad finansowych, nie wykonuje zleceń ani nie zarządza kapitałem użytkowników." },
  status: { title: "Status platformy", visitor: "Gość", visitorDesc: "Zarejestruj się, aby rozpocząć 16-dniowy okres próbny.", backend: "Połączono przez /api", backendDesc: "Rejestracja, logowanie i ankieta są połączone z PostgreSQL.", contact: "ndsp.app@gmail.com", contactDesc: "Oficjalny e-mail dla zapytań i wsparcia." },
  welcome: { title: "Wiadomość powitalna", text: "Z troski o Twoje zadowolenie i aby dać Ci rzetelną szansę doświadczenia siły systemu, oferujemy Ci 16-dniowy okres próbny, aby stopniowo poznać NDSP przed podjęciem jakiegokolwiek zobowiązania.", startTrial: "Rozpocznij próbę", viewJourney: "Zobacz 16-dniową podróż" },
  seats: { title: "Ograniczone miejsca próbne NDSP", subtitle: "Miejsca próbne zostały rozdzielone, aby zapewnić jakość oceny i różnorodność opinii przed płatnym uruchomieniem.", specialist: "Specjalista / Akademik", specialistDesc: "Przydzielone doświadczonym recenzentom, specjalistom i zainteresowanym systematyczną oceną.", regular: "Zwykły użytkownik / Początkujący", regularDesc: "Przydzielone do testowania jasności doświadczenia dla nowych i niespecjalistycznych użytkowników.", special: "Specjalny / Premium", specialDesc: "Przydzielone dla wyróżnionych użytkowników lub z zaawansowanym użytkowaniem i jakościowymi opiniami.", total: "Łączna liczba miejsc próbnych: 50" },
  plans: {
    title: "Plany i funkcje", selectPlan: "Wybierz plan", locked: "Ten plan jest zablokowany podczas bieżącej fazy próbnej.", lockedSub: "Przyciski wyboru i płatności zostaną aktywowane po zakończeniu oficjalnego okresu próbnego.", features: "Funkcje", hidden: "Ukryte w tym planie",
    insight: { name: "Insight", price: "Bezpłatny", desc: "Dla nowych użytkowników, którzy chcą wypróbować system i zrozumieć ogólną koncepcję.", features: ["Ogólny widok stanu rynku", "16-dniowa podróż", "Ankieta dnia 16", "FAQ, bezpieczeństwo i prywatność", "Wyraźna informacja prawna"], hidden: ["Szczegółowy TDL", "Szczegółowy Meeting point", "Meeting point The golden signal", "Black Layer", "API / Webhooks", "Panel administratora"] },
    nmpPro: { name: "Meeting point Pro", price: "$49", desc: "Dla poważnych użytkowników, którzy chcą głębszego zrozumienia kontekstu, płynności i wyrównania.", features: ["TDL — Logika wymiaru czasowego", "Meeting point — Punkt spotkania Nawaf", "Meeting point The golden signal", "Wyraźniejsze raporty interpretacyjne", "Poziomy ryzyka i szerszy kontekst", "Pełny 16-dniowy okres próbny"], hidden: ["Pełna warstwa Black Layer", "Pięć chronionych warstw suwerennych", "API / Webhooks", "Uprawnienia administratora", "Surowa logika"] },
    elite16: { name: "Elite 16", price: "$149", desc: "Dla zaawansowanych użytkowników, którzy chcą najszerszego doświadczenia analitycznego w systemie.", features: ["Szerszy dostęp do logiki 16 warstw", "Black Layer — Adwokat diabła", "Rozszerzona wyjaśnialność", "Zaawansowana analiza ryzyka i kontekst", "Pierwszeństwo w rabatach i ofertach", "Pierwszeństwo w aktualizacjach systemu"], hidden: ["Pięć warstw suwerennych chronionych w UI", "Surowa logika", "Uprawnienia administratora", "Instytucjonalne klucze API"] },
    saas: { name: "NDSP SaaS", price: "Niestandardowy", desc: "Dla firm i podmiotów, które muszą zintegrować NDSP ze swoimi systemami.", features: ["Instytucjonalne klucze API", "Webhooks dla czystych sygnałów ogólnych", "Niestandardowe limity szybkości", "Dzienniki audytu", "Integracja z systemami wewnętrznymi", "Wsparcie techniczne i przegląd operacyjny"], hidden: ["Surowe algorytmy", "W pełni chronione warstwy", "Wewnętrzne tajemnice ważenia", "Uprawnienia właściciela systemu"] },
  },
  trial: { badge: "NDSP Elite Trial • Ograniczona wersja próbna dla instytucji", title: "Witamy w 16-dniowej wersji próbnej NDSP", subtitle: "Ta faza jest poświęcona testowaniu platformy przed płatnym uruchomieniem.", duration: "Czas trwania próby", durationVal: "16 dni od daty aktywacji konta próbnego.", currentPlan: "Bieżący plan", currentPlanVal: "Trial Plan — zorganizowany dostęp próbny przed płatnym uruchomieniem.", benefits: "Korzyści z próby", benefitsVal: "Podstawowy dostęp, zdefiniowane aktywa i uproszczone dane wyjściowe bez ujawniania wewnętrznej logiki.", survey: "Ankieta końca okresu", surveyVal: "Ankieta jest wymagana do oceny doświadczenia i ulepszenia platformy przed rozszerzeniem.", limitedSeats: "Ograniczone miejsca", limitedSeatsVal: "Miejsca próbne są ograniczone i podlegają przeglądowi i aktywacji administracyjnej.", payment: "Bieżąca płatność", paymentVal: "Płatność jest tymczasowo zablokowana do czasu zakończenia fazy próbnej.", start: "Rozumiem, rozpocznij próbę", close: "Zamknij" },
  about: { title: "Czym jest NDSP? I czego nie oferuje?", subtitle: "Ta platforma jest zaprojektowana, aby wyjaśnić granice usług przed rozpoczęciem próby.", whatIs: "Czym jest NDSP?", whatIsItems: ["Platforma wsparcia decyzji i analizy kontekstowej dla rynków.", "Pomaga zrozumieć kontekst i ocenić scenariusze.", "Przedstawia zarządzane i uproszczone dane analityczne.", "Wspiera 16-dniową próbę Elite przed płatnym uruchomieniem."], whatNot: "Czego NDSP NIE oferuje?", whatNotItems: ["Nie jest doradcą finansowym.", "Nie udziela rekomendacji kupna ani sprzedaży.", "Nie wykonuje transakcji ani nie zarządza kapitałem.", "Nie gwarantuje wyników ani dokładności przyszłych scenariuszy."] },
  footer: { disclaimer: "Ostrzeżenie: NDSP to platforma wsparcia decyzji i analizy kontekstowej. Nie udziela porad finansowych, nie wykonuje zleceń ani nie zarządza kapitałem użytkowników.", rights: "Wszelkie prawa zastrzeżone" },
  languageSwitcher: { label: "Język", search: "Szukaj języka...", noResults: "Brak wyników" },
};
