export default {
  nav: { home: "Acasă", plans: "Planuri", trial: "Perioadă de probă", faq: "Întrebări frecvente", login: "Conectare", register: "Înregistrare" },
  hero: { badge: "NDSP Elite Trial • Perioadă de probă instituțională limitată", title: "NDSP — Platforma instituțională de suport decizional", subtitle: "Înțelegeți contextul pieței • Evaluați scenariile • Luați decizii mai informate", disclaimer: "Nu sunt recomandări de tranzacționare — un instrument de analiză educațional gestionat", description: "O platformă sigură de suport decizional care nu oferă recomandări financiare directe, ci prezintă context analitic, starea riscurilor, calitatea deciziei și perspectivă organizată.", startTrial: "Pornire perioadă de probă", viewJourney: "Vizualizare călătorie de 16 zile" },
  warning: { text: "Avertisment: NDSP este o platformă de suport decizional și analiză contextuală. Nu oferă recomandări financiare, nu execută ordine și nu gestionează capitalul utilizatorilor." },
  status: { title: "Starea platformei", visitor: "Vizitator", visitorDesc: "Înregistrați-vă pentru a începe perioada de probă de 16 zile.", backend: "Conectat prin /api", backendDesc: "Înregistrarea, autentificarea și sondajul sunt conectate la PostgreSQL.", contact: "ndsp.app@gmail.com", contactDesc: "Email oficial pentru întrebări și suport." },
  welcome: { title: "Mesaj de bun venit", text: "Din angajamentul nostru față de satisfacția dvs. și pentru a vă oferi o oportunitate echitabilă de a experimenta puterea sistemului, vă oferim o perioadă de probă introductivă de 16 zile pentru a cunoaște NDSP treptat înainte de orice angajament.", startTrial: "Pornire perioadă de probă", viewJourney: "Vizualizare călătorie de 16 zile" },
  seats: { title: "Locuri de probă NDSP limitate", subtitle: "Locurile de probă au fost distribuite pentru a asigura calitatea evaluării și diversitatea feedback-ului înainte de lansarea cu plată.", specialist: "Specialist / Academic", specialistDesc: "Alocat recenzorilor experimentați, specialiștilor și celor interesați de evaluarea sistematică.", regular: "Utilizator obișnuit / Începător", regularDesc: "Alocat pentru a testa claritatea experienței pentru utilizatori noi și nespecialiști.", special: "Special / Premium", specialDesc: "Alocat utilizatorilor distinși sau cu utilizare avansată și feedback calitativ.", total: "Total locuri de probă: 50 de locuri" },
  plans: {
    title: "Planuri și caracteristici", selectPlan: "Selectare plan", locked: "Acest plan este blocat în timpul fazei de probă curente.", lockedSub: "Butoanele de selectare și plată vor fi activate după încheierea perioadei oficiale de probă.", features: "Caracteristici", hidden: "Ascuns în acest plan",
    insight: { name: "Insight", price: "Gratuit", desc: "Pentru utilizatori noi care doresc să experimenteze sistemul și să înțeleagă conceptul general.", features: ["Vedere generală a stării pieței", "Călătorie de 16 zile", "Sondaj de ziua 16", "Întrebări frecvente, securitate și confidențialitate", "Notificare juridică clară"], hidden: ["TDL detaliat", "Meeting point detaliat", "Meeting point The golden signal", "Black Layer", "API / Webhooks", "Panou de administrare"] },
    nmpPro: { name: "Meeting point Pro", price: "$49", desc: "Pentru utilizatori serioși care doresc o înțelegere mai profundă a contextului, lichidității și aliniamentului.", features: ["TDL — Logica dimensiunii temporale", "Meeting point — Punctul de întâlnire Nawaf", "Meeting point The golden signal", "Rapoarte interpretive mai clare", "Niveluri de risc și context mai larg", "Perioadă de probă completă de 16 zile"], hidden: ["Black Layer complet", "Cinci straturi suverane protejate", "API / Webhooks", "Permisiuni de administrator", "Logică brută"] },
    elite16: { name: "Elite 16", price: "$149", desc: "Pentru utilizatori avansați care doresc cea mai largă experiență analitică din sistem.", features: ["Acces mai larg la logica cu 16 straturi", "Black Layer — Avocatul diavolului", "Explicabilitate extinsă", "Analiză avansată a riscurilor și context", "Prioritate la reduceri și oferte", "Prioritate la actualizările sistemului"], hidden: ["Cinci straturi suverane protejate în UI", "Logică brută", "Permisiuni de administrator", "Chei API instituționale"] },
    saas: { name: "NDSP SaaS", price: "Personalizat", desc: "Pentru companii și entități care trebuie să integreze NDSP în sistemele lor.", features: ["Chei API instituționale", "Webhooks pentru semnale generale curate", "Limite de rată personalizate", "Jurnale de audit", "Integrare cu sisteme interne", "Suport tehnic și revizuire operațională"], hidden: ["Algoritmi bruti", "Straturi complet protejate", "Secrete de ponderare internă", "Permisiuni ale proprietarului sistemului"] },
  },
  trial: { badge: "NDSP Elite Trial • Perioadă de probă instituțională limitată", title: "Bun venit la perioada de probă NDSP de 16 zile", subtitle: "Această fază este dedicată testării platformei înainte de lansarea cu plată.", duration: "Durata perioadei de probă", durationVal: "16 zile de la data activării contului de probă.", currentPlan: "Planul curent", currentPlanVal: "Trial Plan — acces de probă organizat înainte de lansarea cu plată.", benefits: "Beneficiile perioadei de probă", benefitsVal: "Acces de bază, active definite și ieșiri simplificate fără dezvăluirea logicii interne.", survey: "Sondaj de sfârșitul perioadei", surveyVal: "Sondajul este necesar pentru a evalua experiența și a îmbunătăți platforma înainte de extindere.", limitedSeats: "Locuri limitate", limitedSeatsVal: "Locurile de probă sunt limitate și supuse revizuirii și activării administrative.", payment: "Plata curentă", paymentVal: "Plata este temporar blocată până la finalizarea fazei de probă.", start: "Am înțeles, pornire perioadă de probă", close: "Închidere" },
  about: { title: "Ce este NDSP? Și ce nu oferă?", subtitle: "Această platformă este concepută pentru a clarifica limitele serviciului înainte de a începe perioada de probă.", whatIs: "Ce este NDSP?", whatIsItems: ["O platformă de suport decizional și analiză contextuală pentru piețe.", "Ajută la înțelegerea contextului și evaluarea scenariilor.", "Prezintă ieșiri analitice gestionate și simplificate.", "Susține perioada de probă Elite de 16 zile înainte de lansarea cu plată."], whatNot: "Ce NU oferă NDSP?", whatNotItems: ["Nu este un consilier financiar.", "Nu oferă recomandări de cumpărare sau vânzare.", "Nu execută tranzacții sau gestionează capital.", "Nu garantează rezultatele sau acuratețea scenariilor viitoare."] },
  footer: { disclaimer: "Avertisment: NDSP este o platformă de suport decizional și analiză contextuală. Nu oferă recomandări financiare, nu execută ordine și nu gestionează capitalul utilizatorilor.", rights: "Toate drepturile rezervate" },
  languageSwitcher: { label: "Limbă", search: "Căutare limbă...", noResults: "Fără rezultate" },
};
