export default {
  nav: { home: "Ana Sayfa", plans: "Planlar", trial: "Deneme", faq: "SSS", login: "Giriş", register: "Kayıt" },
  hero: { badge: "NDSP Elite Trial • Sınırlı Kurumsal Deneme", title: "NDSP — Kurumsal Karar Destek Platformu", subtitle: "Piyasa bağlamını anlayın • Senaryoları değerlendirin • Daha bilinçli kararlar alın", disclaimer: "Ticaret tavsiyesi değil — yönetilen eğitici analiz aracı", description: "Doğrudan finansal tavsiye vermeyip analitik bağlam, risk durumu, karar kalitesi ve organize içgörü sunan güvenli bir karar destek platformu.", startTrial: "Denemeyi Başlat", viewJourney: "16 Günlük Yolculuğu Gör" },
  warning: { text: "Uyarı: NDSP bir karar destek ve bağlamsal analiz platformudur. Finansal tavsiye vermez, emir çalıştırmaz ve kullanıcı sermayesini yönetmez." },
  status: { title: "Platform Durumu", visitor: "Ziyaretçi", visitorDesc: "16 günlük denemenizi başlatmak için kayıt olun.", backend: "/api üzerinden bağlı", backendDesc: "Kayıt, giriş ve anket PostgreSQL'e bağlı.", contact: "ndsp.app@gmail.com", contactDesc: "Sorular ve destek için resmi e-posta." },
  welcome: { title: "Hoş Geldiniz Mesajı", text: "Memnuniyetinize olan bağlılığımız ve sistemin gücünü deneyimlemeniz için adil bir fırsat vermek amacıyla, herhangi bir taahhütte bulunmadan önce NDSP'yi kademeli olarak tanımanız için 16 günlük tanıtım denemesi sunuyoruz.", startTrial: "Denemeyi Başlat", viewJourney: "16 Günlük Yolculuğu Gör" },
  seats: { title: "Sınırlı NDSP Deneme Koltukları", subtitle: "Ücretli lansmandan önce değerlendirme kalitesini ve geri bildirim çeşitliliğini sağlamak için deneme koltukları tahsis edildi.", specialist: "Uzman / Akademisyen", specialistDesc: "Deneyimli değerlendiriciler, uzmanlar ve sistematik değerlendirmeyle ilgilenenler için.", regular: "Normal Kullanıcı / Başlangıç", regularDesc: "Yeni ve uzman olmayan kullanıcılar için deneyim netliğini test etmek için.", special: "Özel / Premium", specialDesc: "Gelişmiş kullanım ve niteliksel geri bildirim ile seçkin kullanıcılar için.", total: "Toplam deneme koltukları: 50" },
  plans: {
    title: "Planlar ve Özellikler", selectPlan: "Plan Seç", locked: "Bu plan mevcut deneme aşamasında kilitli.", lockedSub: "Seçim ve ödeme düğmeleri resmi deneme dönemi sona erdikten sonra etkinleştirilecek.", features: "Özellikler", hidden: "Bu planda gizli",
    insight: { name: "Insight", price: "Ücretsiz", desc: "Sistemi denemek ve genel kavramı anlamak isteyen yeni kullanıcılar için.", features: ["Piyasa durumuna genel bakış", "16 günlük yolculuk", "16. gün anketi", "SSS, güvenlik ve gizlilik", "Net yasal uyarı"], hidden: ["Detaylı TDL", "Detaylı Meeting point", "Meeting point The golden signal", "Black Layer", "API / Webhooks", "Yönetici paneli"] },
    nmpPro: { name: "Meeting point Pro", price: "$49", desc: "Bağlam, likidite ve hizalama hakkında daha derin anlayış isteyen ciddi kullanıcılar için.", features: ["TDL — Zamansal Boyut Mantığı", "Meeting point — Nawaf Buluşma Noktası", "Meeting point The golden signal", "Daha net yorumlayıcı raporlar", "Risk seviyeleri ve daha geniş bağlam", "Tam 16 günlük deneme"], hidden: ["Tam Black Layer", "Beş korumalı egemenlik katmanı", "API / Webhooks", "Yönetici izinleri", "Ham mantık"] },
    elite16: { name: "Elite 16", price: "$149", desc: "Sistem içinde en geniş analitik deneyimi isteyen ileri düzey kullanıcılar için.", features: ["16 katmanlı mantığa daha geniş erişim", "Black Layer — Şeytan'ın Avukatı", "Genişletilmiş Açıklanabilirlik", "Gelişmiş risk analizi ve bağlam", "İndirim ve tekliflerde öncelik", "Sistem güncellemelerinde öncelik"], hidden: ["UI'da beş egemenlik katmanı korumalı", "Ham mantık", "Yönetici izinleri", "Kurumsal API anahtarları"] },
    saas: { name: "NDSP SaaS", price: "Özel", desc: "NDSP'yi sistemlerine entegre etmesi gereken şirket ve kuruluşlar için.", features: ["Kurumsal API anahtarları", "Temiz genel sinyaller için Webhooks", "Özel hız sınırları", "Denetim günlükleri", "İç sistemlerle entegrasyon", "Teknik destek ve operasyonel inceleme"], hidden: ["Ham algoritmalar", "Tamamen korumalı katmanlar", "Dahili ağırlıklandırma sırları", "Sistem sahibi izinleri"] },
  },
  trial: { badge: "NDSP Elite Trial • Sınırlı Kurumsal Deneme", title: "NDSP 16 Günlük Denemeye Hoş Geldiniz", subtitle: "Bu aşama ücretli lansmandan önce platformu test etmeye adanmış.", duration: "Deneme Süresi", durationVal: "Deneme hesabı aktivasyon tarihinden itibaren 16 gün.", currentPlan: "Mevcut Plan", currentPlanVal: "Trial Plan — ücretli lansmandan önce organize deneme erişimi.", benefits: "Deneme Avantajları", benefitsVal: "İç mantığı açıklamadan temel erişim, tanımlı varlıklar ve basitleştirilmiş çıktılar.", survey: "Dönem Sonu Anketi", surveyVal: "Deneyimi değerlendirmek ve genişlemeden önce platformu geliştirmek için anket gerekli.", limitedSeats: "Sınırlı Koltuklar", limitedSeatsVal: "Deneme koltukları sınırlı ve inceleme ile idari aktivasyona tabi.", payment: "Mevcut Ödeme", paymentVal: "Deneme aşaması tamamlanana kadar ödeme geçici olarak kilitli.", start: "Anladım, Denemeyi Başlat", close: "Kapat" },
  about: { title: "NDSP nedir? Ve ne sunmaz?", subtitle: "Bu platform, denemeye başlamadan önce hizmet sınırlarını netleştirmek için tasarlanmıştır.", whatIs: "NDSP nedir?", whatIsItems: ["Piyasalar için karar destek ve bağlamsal analiz platformu.", "Bağlamı anlamaya ve senaryoları değerlendirmeye yardımcı olur.", "Yönetilen ve basitleştirilmiş analitik çıktılar sunar.", "Ücretli lansmandan önce Elite 16 günlük denemeyi destekler."], whatNot: "NDSP ne SUNMAZ?", whatNotItems: ["Finansal danışman değildir.", "Alım veya satım tavsiyesi vermez.", "İşlem yapmaz veya sermaye yönetmez.", "Sonuçları veya gelecekteki senaryoların doğruluğunu garanti etmez."] },
  footer: { disclaimer: "Uyarı: NDSP bir karar destek ve bağlamsal analiz platformudur. Finansal tavsiye vermez, emir çalıştırmaz ve kullanıcı sermayesini yönetmez.", rights: "Tüm hakları saklıdır" },
  languageSwitcher: { label: "Dil", search: "Dil ara...", noResults: "Sonuç yok" },
};
