export const CONTRACT_VERSION = '1.0.0';

export const DIRECTIONS = Object.freeze({
  BUY: 'BUY',
  SELL: 'SELL',
  NEUTRAL: 'NEUTRAL',
});

export const CLARITIES = Object.freeze({
  EXPLICIT: 'EXPLICIT',
  NON_EXPLICIT: 'NON_EXPLICIT',
  TRANSITIONAL: 'TRANSITIONAL',
  NEUTRAL: 'NEUTRAL',
});

export const HORIZONS = Object.freeze({
  EXTENDED: 'EXTENDED',
  NARROW: 'NARROW',
  NEUTRAL: 'NEUTRAL',
});

export const CLASSIFICATIONS = Object.freeze({
  EXPLICIT_EXTENDED_BUY: 'EXPLICIT_EXTENDED_BUY',
  EXPLICIT_EXTENDED_SELL: 'EXPLICIT_EXTENDED_SELL',
  NON_EXPLICIT_NARROW_BUY: 'NON_EXPLICIT_NARROW_BUY',
  NON_EXPLICIT_NARROW_SELL: 'NON_EXPLICIT_NARROW_SELL',
  EXPANSION_BALANCE: 'EXPANSION_BALANCE',
  CONTRACTION_BALANCE: 'CONTRACTION_BALANCE',
  SHORT_COVERING_BUY: 'SHORT_COVERING_BUY',
  LONG_LIQUIDATION_SELL: 'LONG_LIQUIDATION_SELL',
  DIRECT_BUY: 'DIRECT_BUY',
  DIRECT_SELL: 'DIRECT_SELL',
  SHORT_COVERING_ONLY: 'SHORT_COVERING_ONLY',
  LONG_LIQUIDATION_ONLY: 'LONG_LIQUIDATION_ONLY',
  FULL_NEUTRAL: 'FULL_NEUTRAL',
});
