# __SERVICE_ID__ — __SERVICE_NAME__ Contract

## Purpose

__SERVICE_NAME__ service generated by DEV-001.

## Endpoints

- GET /health
- GET /version
- GET /about
- GET /service-info

## Requirements

- Must use ENG-001.
- Must not bootstrap Express directly.
