export default {
  nav: { home: "Domů", plans: "Plány", trial: "Zkušební verze", faq: "Časté otázky", login: "Přihlásit se", register: "Registrovat se" },
  hero: { badge: "NDSP Elite Trial • Omezená institucionální zkušební verze", title: "NDSP — Institucionální platforma pro podporu rozhodování", subtitle: "Pochopte tržní kontext • Vyhodnoťte scénáře • Přijímejte informovanější rozhodnutí", disclaimer: "Nejsou to obchodní doporučení — řízený vzdělávací analytický nástroj", description: "Bezpečná platforma pro podporu rozhodování, která neposkytuje přímá finanční doporučení, ale prezentuje analytický kontext, stav rizik, kvalitu rozhodnutí a organizovaný přehled.", startTrial: "Spustit zkušební verzi", viewJourney: "Zobrazit 16denní cestu" },
  warning: { text: "Upozornění: NDSP je platforma pro podporu rozhodování a kontextovou analýzu. Neposkytuje finanční doporučení, neprovádí příkazy a nespravuje kapitál uživatelů." },
  status: { title: "Stav platformy", visitor: "Návštěvník", visitorDesc: "Registrujte se a spusťte svou 16denní zkušební verzi.", backend: "Připojeno přes /api", backendDesc: "Registrace, přihlášení a průzkum jsou připojeny k PostgreSQL.", contact: "ndsp.app@gmail.com", contactDesc: "Oficiální e-mail pro dotazy a podporu." },
  welcome: { title: "Uvítací zpráva", text: "Z naší oddanosti vaší spokojenosti a abychom vám dali spravedlivou příležitost zažít sílu systému, nabízíme vám 16denní úvodní zkušební verzi, abyste před jakýmkoli závazkem postupně poznali NDSP.", startTrial: "Spustit zkušební verzi", viewJourney: "Zobrazit 16denní cestu" },
  seats: { title: "Omezená zkušební místa NDSP", subtitle: "Zkušební místa byla rozdělena, aby zajistila kvalitu hodnocení a rozmanitost zpětné vazby před placeným spuštěním.", specialist: "Specialista / Akademik", specialistDesc: "Přiděleno zkušeným recenzentům, specialistům a zájemcům o systematické hodnocení.", regular: "Běžný uživatel / Začátečník", regularDesc: "Přiděleno pro testování srozumitelnosti zkušenosti pro nové a neodborné uživatele.", special: "Speciální / Prémiové", specialDesc: "Přiděleno pro vynikající uživatele nebo s pokročilým využíváním a kvalitativní zpětnou vazbou.", total: "Celkový počet zkušebních míst: 50 míst" },
  plans: {
    title: "Plány a funkce", selectPlan: "Vybrat plán", locked: "Tento plán je uzamčen během aktuální zkušební fáze.", lockedSub: "Tlačítka výběru a platby budou aktivována po skončení oficiálního zkušebního období.", features: "Funkce", hidden: "Skryto v tomto plánu",
    insight: { name: "Insight", price: "Zdarma", desc: "Pro nové uživatele, kteří chtějí vyzkoušet systém a pochopit obecný koncept.", features: ["Obecný přehled stavu trhu", "16denní cesta", "Průzkum dne 16", "Časté otázky, bezpečnost a soukromí", "Jasné právní upozornění"], hidden: ["Podrobné TDL", "Podrobné NMP", "NMP Golden Alignment", "Black Layer", "API / Webhooks", "Panel správce"] },
    nmpPro: { name: "NMP Pro", price: "$49", desc: "Pro vážné uživatele, kteří chtějí hlubší pochopení kontextu, likvidity a zarovnání.", features: ["TDL — Logika časové dimenze", "NMP — Nawafův setkávací bod", "NMP Golden Alignment", "Jasnější interpretační zprávy", "Úrovně rizika a širší kontext", "Úplná 16denní zkušební verze"], hidden: ["Úplná vrstva Black Layer", "Pět chráněných suverénních vrstev", "API / Webhooks", "Administrátorská oprávnění", "Surová logika"] },
    elite16: { name: "Elite 16", price: "$149", desc: "Pro pokročilé uživatele, kteří chtějí nejširší analytický zážitek v systému.", features: ["Širší přístup k logice 16 vrstev", "Black Layer — Ďáblův advokát", "Rozšířená vysvětlitelnost", "Pokročilá analýza rizik a kontext", "Priorita na slevy a nabídky", "Priorita na aktualizace systému"], hidden: ["Pět suverénních vrstev chráněných v UI", "Surová logika", "Administrátorská oprávnění", "Institucionální klíče API"] },
    saas: { name: "NDSP SaaS", price: "Vlastní", desc: "Pro společnosti a subjekty, které potřebují integrovat NDSP do svých systémů.", features: ["Institucionální klíče API", "Webhooks pro čisté obecné signály", "Vlastní limity rychlosti", "Auditní záznamy", "Integrace s interními systémy", "Technická podpora a provozní přezkum"], hidden: ["Surové algoritmy", "Plně chráněné vrstvy", "Vnitřní vážní tajemství", "Oprávnění vlastníka systému"] },
  },
  trial: { badge: "NDSP Elite Trial • Omezená institucionální zkušební verze", title: "Vítejte v 16denní zkušební verzi NDSP", subtitle: "Tato fáze je věnována testování platformy před placeným spuštěním.", duration: "Délka zkušební verze", durationVal: "16 dní od data aktivace zkušebního účtu.", currentPlan: "Aktuální plán", currentPlanVal: "Trial Plan — organizovaný zkušební přístup před placeným spuštěním.", benefits: "Výhody zkušební verze", benefitsVal: "Základní přístup, definovaná aktiva a zjednodušené výstupy bez odhalení vnitřní logiky.", survey: "Průzkum na konci období", surveyVal: "Průzkum je nutný pro hodnocení zkušenosti a zlepšení platformy před rozšířením.", limitedSeats: "Omezená místa", limitedSeatsVal: "Zkušební místa jsou omezená a podléhají přezkoumání a administrativní aktivaci.", payment: "Aktuální platba", paymentVal: "Platba je dočasně uzamčena až do dokončení zkušební fáze.", start: "Rozumím, spustit zkušební verzi", close: "Zavřít" },
  about: { title: "Co je NDSP? A co nenabízí?", subtitle: "Tato platforma je navržena k objasnění hranic služby před zahájením zkušební verze.", whatIs: "Co je NDSP?", whatIsItems: ["Platforma pro podporu rozhodování a kontextovou analýzu pro trhy.", "Pomáhá pochopit kontext a vyhodnotit scénáře.", "Prezentuje řízené a zjednodušené analytické výstupy.", "Podporuje 16denní zkušební verzi Elite před placeným spuštěním."], whatNot: "Co NDSP nenabízí?", whatNotItems: ["Není finančním poradcem.", "Neposkytuje doporučení k nákupu ani prodeji.", "Neprovádí transakce ani nespravuje kapitál.", "Nezaručuje výsledky ani přesnost budoucích scénářů."] },
  footer: { disclaimer: "Upozornění: NDSP je platforma pro podporu rozhodování a kontextovou analýzu. Neposkytuje finanční doporučení, neprovádí příkazy a nespravuje kapitál uživatelů.", rights: "Všechna práva vyhrazena" },
  languageSwitcher: { label: "Jazyk", search: "Hledat jazyk...", noResults: "Žádné výsledky" },
};
