export default {
  nav: { home: "Főoldal", plans: "Csomagok", trial: "Próbaidőszak", faq: "GYIK", login: "Bejelentkezés", register: "Regisztráció" },
  hero: { badge: "NDSP Elite Trial • Korlátozott intézményi próba", title: "NDSP — Intézményi döntéstámogató platform", subtitle: "Értse meg a piaci kontextust • Értékelje a forgatókönyveket • Hozzon megalapozottabb döntéseket", disclaimer: "Nem kereskedési ajánlások — irányított oktatási elemzési eszköz", description: "Biztonságos döntéstámogató platform, amely nem ad közvetlen pénzügyi ajánlásokat, hanem analitikus kontextust, kockázati állapotot, döntési minőséget és szervezett betekintést mutat be.", startTrial: "Próba indítása", viewJourney: "16 napos utazás megtekintése" },
  warning: { text: "Figyelmeztetés: Az NDSP döntéstámogató és kontextuális elemzési platform. Nem ad pénzügyi ajánlásokat, nem hajt végre megbízásokat és nem kezeli a felhasználók tőkéjét." },
  status: { title: "Platform állapota", visitor: "Látogató", visitorDesc: "Regisztráljon a 16 napos próbaidőszak elindításához.", backend: "/api-n keresztül csatlakoztatva", backendDesc: "A regisztráció, bejelentkezés és felmérés PostgreSQL-hez csatlakozik.", contact: "ndsp.app@gmail.com", contactDesc: "Hivatalos e-mail kérdések és támogatás céljából." },
  welcome: { title: "Üdvözlő üzenet", text: "Az Ön elégedettségének iránti elkötelezettségünk és a rendszer erejének megtapasztalásához való méltányos lehetőség biztosítása érdekében 16 napos bevezető próbát kínálunk, hogy bármilyen kötelezettség előtt fokozatosan megismerje az NDSP-t.", startTrial: "Próba indítása", viewJourney: "16 napos utazás megtekintése" },
  seats: { title: "Korlátozott NDSP próbahelyek", subtitle: "A próbahelyeket az értékelés minőségének és a visszajelzések sokféleségének biztosítása érdekében osztották szét a fizetős indítás előtt.", specialist: "Szakértő / Tudományos", specialistDesc: "Tapasztalt értékelők, szakértők és szisztematikus értékelés iránt érdeklődők számára.", regular: "Általános felhasználó / Kezdő", regularDesc: "Az élmény tisztaságának tesztelésére új és nem szakértő felhasználók számára.", special: "Különleges / Prémium", specialDesc: "Kiemelkedő felhasználók vagy fejlett felhasználással és minőségi visszajelzéssel rendelkezők számára.", total: "Összes próbahely: 50 hely" },
  plans: {
    title: "Csomagok és funkciók", selectPlan: "Csomag kiválasztása", locked: "Ez a csomag a jelenlegi próbafázis alatt zárolt.", lockedSub: "A kiválasztó és fizetési gombok a hivatalos próbaidőszak lejárta után aktiválódnak.", features: "Funkciók", hidden: "Ebben a csomagban rejtett",
    insight: { name: "Insight", price: "Ingyenes", desc: "Új felhasználók számára, akik ki akarják próbálni a rendszert és megérteni az általános koncepciót.", features: ["Általános piaci állapotáttekintés", "16 napos utazás", "16. napi felmérés", "GYIK, biztonság és adatvédelem", "Egyértelmű jogi értesítés"], hidden: ["Részletes TDL", "Részletes NMP", "NMP Golden Alignment", "Black Layer", "API / Webhooks", "Admin panel"] },
    nmpPro: { name: "NMP Pro", price: "$49", desc: "Komoly felhasználók számára, akik mélyebb megértést akarnak a kontextusról, likviditásról és összehangolásról.", features: ["TDL — Időbeli dimenziós logika", "NMP — Nawaf találkozópontja", "NMP Golden Alignment", "Egyértelmébb értelmező jelentések", "Kockázati szintek és szélesebb kontextus", "Teljes 16 napos próba"], hidden: ["Teljes Black Layer", "Öt védett szuverén réteg", "API / Webhooks", "Admin jogosultságok", "Nyers logika"] },
    elite16: { name: "Elite 16", price: "$149", desc: "Fejlett felhasználók számára, akik a rendszeren belül a legszélesebb analitikai élményt akarják.", features: ["Szélesebb hozzáférés a 16 rétegű logikához", "Black Layer — Az ördög ügyvédje", "Kiterjesztett magyarázhatóság", "Fejlett kockázatelemzés és kontextus", "Elsőbbség kedvezményeken és ajánlatokon", "Elsőbbség rendszerfrissítéseknél"], hidden: ["Öt szuverén réteg védve a UI-ban", "Nyers logika", "Admin jogosultságok", "Intézményi API kulcsok"] },
    saas: { name: "NDSP SaaS", price: "Egyéni", desc: "Vállalatok és szervezetek számára, amelyeknek az NDSP-t be kell integrálniuk rendszereikbe.", features: ["Intézményi API kulcsok", "Webhooks tiszta általános jelzésekhez", "Egyéni sebességkorlátok", "Audit naplók", "Integráció belső rendszerekkel", "Műszaki támogatás és operatív felülvizsgálat"], hidden: ["Nyers algoritmusok", "Teljesen védett rétegek", "Belső súlyozási titkok", "Rendszertulajdonosi jogosultságok"] },
  },
  trial: { badge: "NDSP Elite Trial • Korlátozott intézményi próba", title: "Üdvözöljük az NDSP 16 napos próbájában", subtitle: "Ez a fázis a platform tesztelésének van szentelve a fizetős indítás előtt.", duration: "Próbaidőszak hossza", durationVal: "16 nap a próbafiók aktiválásának dátumától.", currentPlan: "Jelenlegi csomag", currentPlanVal: "Trial Plan — szervezett próbahozzáférés a fizetős indítás előtt.", benefits: "Próba előnyei", benefitsVal: "Alapvető hozzáférés, meghatározott eszközök és egyszerűsített kimenetek a belső logika felfedése nélkül.", survey: "Időszak végi felmérés", surveyVal: "Felmérés szükséges az élmény értékeléséhez és a platform fejlesztéséhez a terjeszkedés előtt.", limitedSeats: "Korlátozott helyek", limitedSeatsVal: "A próbahelyek korlátozottak és felülvizsgálatnak és adminisztratív aktiválásnak vannak alávetve.", payment: "Jelenlegi fizetés", paymentVal: "A fizetés ideiglenesen zárolva, amíg a próbafázis be nem fejeződik.", start: "Értettem, próba indítása", close: "Bezárás" },
  about: { title: "Mi az NDSP? És mit nem kínál?", subtitle: "Ez a platform a szolgáltatás határainak tisztázására lett tervezve a próba megkezdése előtt.", whatIs: "Mi az NDSP?", whatIsItems: ["Döntéstámogató és kontextuális elemzési platform piacok számára.", "Segít megérteni a kontextust és értékelni a forgatókönyveket.", "Irányított és egyszerűsített analitikai kimeneteket mutat be.", "Támogatja a fizetős indítás előtti Elite 16 napos próbát."], whatNot: "Mit NEM kínál az NDSP?", whatNotItems: ["Nem pénzügyi tanácsadó.", "Nem ad vételi vagy eladási ajánlásokat.", "Nem hajt végre tranzakciókat vagy kezel tőkét.", "Nem garantálja az eredményeket vagy a jövőbeli forgatókönyvek pontosságát."] },
  footer: { disclaimer: "Figyelmeztetés: Az NDSP döntéstámogató és kontextuális elemzési platform. Nem ad pénzügyi ajánlásokat, nem hajt végre megbízásokat és nem kezeli a felhasználók tőkéjét.", rights: "Minden jog fenntartva" },
  languageSwitcher: { label: "Nyelv", search: "Nyelv keresése...", noResults: "Nincs eredmény" },
};
