export default {
  nav: { home: "Home", plans: "Piani", trial: "Prova", faq: "FAQ", login: "Accedi", register: "Registrati" },
  hero: { badge: "NDSP Elite Trial • Prova istituzionale limitata", title: "NDSP — Piattaforma istituzionale di supporto alle decisioni", subtitle: "Comprendi il contesto di mercato • Valuta scenari • Prendi decisioni più informate", disclaimer: "Non raccomandazioni di trading — uno strumento di analisi educativa governato", description: "Una piattaforma sicura di supporto alle decisioni che non fornisce raccomandazioni finanziarie dirette, ma presenta contesto analitico, stato del rischio, qualità delle decisioni e visione organizzata.", startTrial: "Inizia la prova", viewJourney: "Vedi il percorso di 16 giorni" },
  warning: { text: "Avviso: NDSP è una piattaforma di supporto alle decisioni e analisi contestuale. Non fornisce raccomandazioni finanziarie, non esegue ordini e non gestisce il capitale degli utenti." },
  status: { title: "Stato della piattaforma", visitor: "Visitatore", visitorDesc: "Registrati per iniziare la prova di 16 giorni.", backend: "Connesso via /api", backendDesc: "Registrazione, accesso e sondaggio connessi a PostgreSQL.", contact: "ndsp.app@gmail.com", contactDesc: "Email ufficiale per richieste e supporto." },
  welcome: { title: "Messaggio di benvenuto", text: "Per il nostro impegno verso la tua soddisfazione e per darti una giusta opportunità di sperimentare la potenza del sistema, ti offriamo una prova introduttiva di 16 giorni per conoscere NDSP gradualmente prima di qualsiasi impegno.", startTrial: "Inizia la prova", viewJourney: "Vedi il percorso di 16 giorni" },
  seats: { title: "Posti prova NDSP limitati", subtitle: "I posti prova sono stati distribuiti per garantire la qualità della valutazione e la diversità del feedback prima del lancio a pagamento.", specialist: "Specialista / Accademico", specialistDesc: "Assegnato a revisori esperti, specialisti e interessati alla valutazione sistematica.", regular: "Utente normale / Principiante", regularDesc: "Assegnato per testare la chiarezza dell'esperienza per utenti nuovi e non specializzati.", special: "Speciale / Premium", specialDesc: "Assegnato per utenti distinti o con utilizzo avanzato e feedback qualitativi.", total: "Totale posti prova: 50 posti" },
  plans: {
    title: "Piani e funzionalità", selectPlan: "Seleziona piano", locked: "Questo piano è bloccato durante la fase di prova corrente.", lockedSub: "I pulsanti di selezione e pagamento saranno attivati dopo la fine del periodo di prova ufficiale.", features: "Funzionalità", hidden: "Nascosto in questo piano",
    insight: { name: "Insight", price: "Gratuito", desc: "Per nuovi utenti che vogliono sperimentare il sistema e comprendere il concetto generale.", features: ["Panoramica generale dello stato del mercato", "Percorso di 16 giorni", "Sondaggio del giorno 16", "FAQ, sicurezza e privacy", "Avviso legale chiaro"], hidden: ["TDL dettagliato", "NMP dettagliato", "NMP Golden Alignment", "Black Layer", "API / Webhooks", "Pannello di amministrazione"] },
    nmpPro: { name: "NMP Pro", price: "$49", desc: "Per utenti seri che vogliono una comprensione più profonda del contesto, della liquidità e dell'allineamento.", features: ["TDL — Logica della Dimensione Temporale", "NMP — Punto di incontro Nawaf", "NMP Golden Alignment", "Rapporti interpretativi più chiari", "Livelli di rischio e contesto più ampio", "Prova completa di 16 giorni"], hidden: ["Black Layer completo", "Cinque livelli sovrani protetti", "API / Webhooks", "Autorizzazioni di amministrazione", "Logica grezza"] },
    elite16: { name: "Elite 16", price: "$149", desc: "Per utenti avanzati che vogliono l'esperienza analitica più ampia all'interno del sistema.", features: ["Accesso più ampio alla logica a 16 livelli", "Black Layer — Avvocato del diavolo", "Spiegabilità estesa", "Analisi del rischio avanzata e contesto", "Priorità su sconti e offerte", "Priorità sugli aggiornamenti del sistema"], hidden: ["Cinque livelli sovrani protetti nell'UI", "Logica grezza", "Autorizzazioni di amministrazione", "Chiavi API istituzionali"] },
    saas: { name: "NDSP SaaS", price: "Personalizzato", desc: "Per aziende ed enti che necessitano di integrare NDSP nei loro sistemi.", features: ["Chiavi API istituzionali", "Webhooks per segnali generali puliti", "Limiti di velocità personalizzati", "Registri di audit", "Integrazione con sistemi interni", "Supporto tecnico e revisione operativa"], hidden: ["Algoritmi grezzi", "Livelli completamente protetti", "Segreti di ponderazione interna", "Autorizzazioni del proprietario del sistema"] },
  },
  trial: { badge: "NDSP Elite Trial • Prova istituzionale limitata", title: "Benvenuto nella prova NDSP di 16 giorni", subtitle: "Questa fase è dedicata al test della piattaforma prima del lancio a pagamento.", duration: "Durata della prova", durationVal: "16 giorni dalla data di attivazione dell'account di prova.", currentPlan: "Piano corrente", currentPlanVal: "Trial Plan — accesso prova organizzato prima del lancio a pagamento.", benefits: "Vantaggi della prova", benefitsVal: "Accesso di base, asset definiti e output semplificati senza rivelare la logica interna.", survey: "Sondaggio di fine periodo", surveyVal: "Il sondaggio è necessario per valutare l'esperienza e migliorare la piattaforma prima dell'espansione.", limitedSeats: "Posti limitati", limitedSeatsVal: "I posti prova sono limitati e soggetti a revisione e attivazione amministrativa.", payment: "Pagamento corrente", paymentVal: "Il pagamento è temporaneamente bloccato fino al completamento della fase di prova.", start: "Capito, inizia la prova", close: "Chiudi" },
  about: { title: "Cos'è NDSP? E cosa non offre?", subtitle: "Questa piattaforma è progettata per chiarire i limiti del servizio prima di iniziare la prova.", whatIs: "Cos'è NDSP?", whatIsItems: ["Una piattaforma di supporto alle decisioni e analisi contestuale per i mercati.", "Aiuta a comprendere il contesto e valutare gli scenari.", "Presenta output analitici governati e semplificati.", "Supporta la prova Elite di 16 giorni prima del lancio a pagamento."], whatNot: "Cosa NON offre NDSP?", whatNotItems: ["Non è un consulente finanziario.", "Non fornisce raccomandazioni di acquisto o vendita.", "Non esegue transazioni né gestisce capitale.", "Non garantisce risultati o precisione degli scenari futuri."] },
  footer: { disclaimer: "Avviso: NDSP è una piattaforma di supporto alle decisioni e analisi contestuale. Non fornisce raccomandazioni finanziarie, non esegue ordini e non gestisce il capitale degli utenti.", rights: "Tutti i diritti riservati" },
  languageSwitcher: { label: "Lingua", search: "Cerca lingua...", noResults: "Nessun risultato" },
};
