export default {
  nav: { home: "Laman Utama", plans: "Pelan", trial: "Percubaan", faq: "Soalan Lazim", login: "Log Masuk", register: "Daftar" },
  hero: { badge: "NDSP Elite Trial • Percubaan Institusi Terhad", title: "NDSP — Platform Sokongan Keputusan Institusi", subtitle: "Fahami konteks pasaran • Nilai senario • Buat keputusan lebih bermaklumat", disclaimer: "Bukan cadangan perdagangan — alat analisis pendidikan yang dikawal", description: "Platform sokongan keputusan selamat yang tidak memberikan cadangan kewangan langsung, tetapi memaparkan konteks analitis, status risiko, kualiti keputusan, dan wawasan teratur.", startTrial: "Mulakan Percubaan", viewJourney: "Lihat Perjalanan 16 Hari" },
  warning: { text: "Amaran: NDSP adalah platform sokongan keputusan dan analisis kontekstual. Ia tidak memberikan cadangan kewangan, tidak melaksanakan perintah, dan tidak menguruskan modal pengguna." },
  status: { title: "Status Platform", visitor: "Pelawat", visitorDesc: "Daftar untuk memulakan percubaan 16 hari anda.", backend: "Disambungkan melalui /api", backendDesc: "Pendaftaran, log masuk dan tinjauan disambungkan ke PostgreSQL.", contact: "ndsp.app@gmail.com", contactDesc: "E-mel rasmi untuk pertanyaan dan sokongan." },
  welcome: { title: "Mesej Selamat Datang", text: "Demi kepuasan anda dan untuk memberi anda peluang yang adil untuk merasai kuasa sistem, kami menawarkan percubaan pengenalan 16 hari untuk mengenali NDSP secara beransur-ansur sebelum sebarang komitmen.", startTrial: "Mulakan Percubaan", viewJourney: "Lihat Perjalanan 16 Hari" },
  seats: { title: "Tempat Percubaan NDSP Terhad", subtitle: "Tempat percubaan telah dibahagikan untuk memastikan kualiti penilaian dan kepelbagaian maklum balas sebelum pelancaran berbayar.", specialist: "Pakar / Akademik", specialistDesc: "Diperuntukkan untuk pengulas berpengalaman, pakar, dan mereka yang berminat dengan penilaian sistematik.", regular: "Pengguna Biasa / Pemula", regularDesc: "Diperuntukkan untuk menguji kejelasan pengalaman bagi pengguna baharu dan bukan pakar.", special: "Khas / Premium", specialDesc: "Diperuntukkan untuk pengguna cemerlang atau dengan penggunaan lanjutan dan maklum balas kualitatif.", total: "Jumlah tempat percubaan: 50 tempat" },
  plans: {
    title: "Pelan dan Ciri", selectPlan: "Pilih Pelan", locked: "Pelan ini dikunci semasa fasa percubaan semasa.", lockedSub: "Butang pilih dan bayar akan diaktifkan selepas tempoh percubaan rasmi tamat.", features: "Ciri", hidden: "Tersembunyi dalam pelan ini",
    insight: { name: "Insight", price: "Percuma", desc: "Untuk pengguna baharu yang ingin mencuba sistem dan memahami konsep umum.", features: ["Pandangan umum status pasaran", "Perjalanan 16 hari", "Tinjauan hari ke-16", "Soalan Lazim, keselamatan dan privasi", "Notis undang-undang yang jelas"], hidden: ["TDL terperinci", "NMP terperinci", "NMP Golden Alignment", "Black Layer", "API / Webhooks", "Panel pentadbir"] },
    nmpPro: { name: "NMP Pro", price: "$49", desc: "Untuk pengguna serius yang mahukan pemahaman lebih mendalam tentang konteks, kecairan dan penjajaran.", features: ["TDL — Logik Dimensi Temporal", "NMP — Titik Pertemuan Nawaf", "NMP Golden Alignment", "Laporan interpretatif yang lebih jelas", "Tahap risiko dan konteks lebih luas", "Percubaan penuh 16 hari"], hidden: ["Black Layer penuh", "Lima lapisan berdaulat dilindungi", "API / Webhooks", "Kebenaran pentadbir", "Logik mentah"] },
    elite16: { name: "Elite 16", price: "$149", desc: "Untuk pengguna lanjutan yang mahukan pengalaman analitis paling luas dalam sistem.", features: ["Akses lebih luas kepada logik 16 lapisan", "Black Layer — Peguam Bela Syaitan", "Kebolehjelasan diperluas", "Analisis risiko lanjutan dan konteks", "Keutamaan pada diskaun dan tawaran", "Keutamaan pada kemas kini sistem"], hidden: ["Lima lapisan berdaulat dilindungi dalam UI", "Logik mentah", "Kebenaran pentadbir", "Kunci API institusi"] },
    saas: { name: "NDSP SaaS", price: "Tersuai", desc: "Untuk syarikat dan entiti yang perlu mengintegrasikan NDSP dalam sistem mereka.", features: ["Kunci API institusi", "Webhooks untuk isyarat umum yang bersih", "Had kadar tersuai", "Log audit", "Integrasi dengan sistem dalaman", "Sokongan teknikal dan semakan operasi"], hidden: ["Algoritma mentah", "Lapisan dilindungi sepenuhnya", "Rahsia pemberat dalaman", "Kebenaran pemilik sistem"] },
  },
  trial: { badge: "NDSP Elite Trial • Percubaan Institusi Terhad", title: "Selamat Datang ke Percubaan NDSP 16 Hari", subtitle: "Fasa ini didedikasikan untuk menguji platform sebelum pelancaran berbayar.", duration: "Tempoh Percubaan", durationVal: "16 hari dari tarikh pengaktifan akaun percubaan.", currentPlan: "Pelan Semasa", currentPlanVal: "Trial Plan — akses percubaan teratur sebelum pelancaran berbayar.", benefits: "Manfaat Percubaan", benefitsVal: "Akses asas, aset yang ditentukan, dan output dipermudahkan tanpa mendedahkan logik dalaman.", survey: "Tinjauan Akhir Tempoh", surveyVal: "Tinjauan diperlukan untuk menilai pengalaman dan meningkatkan platform sebelum pengembangan.", limitedSeats: "Tempat Terhad", limitedSeatsVal: "Tempat percubaan terhad dan tertakluk kepada semakan dan pengaktifan pentadbiran.", payment: "Pembayaran Semasa", paymentVal: "Pembayaran dikunci sementara sehingga fasa percubaan selesai.", start: "Faham, Mulakan Percubaan", close: "Tutup" },
  about: { title: "Apakah NDSP? Dan apa yang tidak ditawarkannya?", subtitle: "Platform ini direka untuk menjelaskan had perkhidmatan sebelum memulakan percubaan.", whatIs: "Apakah NDSP?", whatIsItems: ["Platform sokongan keputusan dan analisis kontekstual untuk pasaran.", "Membantu memahami konteks dan menilai senario.", "Memaparkan output analitis yang dikawal dan dipermudahkan.", "Menyokong percubaan Elite 16 hari sebelum pelancaran berbayar."], whatNot: "Apa yang TIDAK ditawarkan NDSP?", whatNotItems: ["Bukan penasihat kewangan.", "Tidak memberikan cadangan beli atau jual.", "Tidak melaksanakan transaksi atau menguruskan modal.", "Tidak menjamin keputusan atau ketepatan senario masa hadapan."] },
  footer: { disclaimer: "Amaran: NDSP adalah platform sokongan keputusan dan analisis kontekstual. Ia tidak memberikan cadangan kewangan, tidak melaksanakan perintah, dan tidak menguruskan modal pengguna.", rights: "Hak cipta terpelihara" },
  languageSwitcher: { label: "Bahasa", search: "Cari bahasa...", noResults: "Tiada keputusan" },
};
