export default {
  nav: { home: "Hem", plans: "Planer", trial: "Provperiod", faq: "Vanliga frågor", login: "Logga in", register: "Registrera" },
  hero: { badge: "NDSP Elite Trial • Begränsad institutionell provperiod", title: "NDSP — Institutionell beslutsstödplattform", subtitle: "Förstå marknadskontext • Utvärdera scenarier • Fatta mer välgrundade beslut", disclaimer: "Inga handelsrekommendationer — ett styrt pedagogiskt analysverktyg", description: "En säker beslutsstödplattform som inte ger direkta finansiella rekommendationer utan presenterar analytisk kontext, riskstatus, beslutskvalitet och organiserade insikter.", startTrial: "Starta provperiod", viewJourney: "Se 16-dagarsresan" },
  warning: { text: "Varning: NDSP är en plattform för beslutsstöd och kontextuell analys. Den ger inga finansiella rekommendationer, utför inga order och förvaltar inget användarkapital." },
  status: { title: "Plattformsstatus", visitor: "Besökare", visitorDesc: "Registrera dig för att starta din 16-dagars provperiod.", backend: "Ansluten via /api", backendDesc: "Registrering, inloggning och enkät är anslutna till PostgreSQL.", contact: "ndsp.app@gmail.com", contactDesc: "Officiell e-post för förfrågningar och support." },
  welcome: { title: "Välkomstmeddelande", text: "Av vår strävan efter din tillfredsställelse och för att ge dig en rättvis möjlighet att uppleva systemets kraft erbjuder vi dig en 16-dagars introduktionsprovperiod för att lära känna NDSP gradvis innan något åtagande.", startTrial: "Starta provperiod", viewJourney: "Se 16-dagarsresan" },
  seats: { title: "Begränsade NDSP-provplatser", subtitle: "Provplatser har fördelats för att säkerställa utvärderingskvalitet och diversitet av feedback före den betalda lanseringen.", specialist: "Specialist / Akademiker", specialistDesc: "Tilldelad erfarna granskare, specialister och de intresserade av systematisk utvärdering.", regular: "Vanlig användare / Nybörjare", regularDesc: "Tilldelad för att testa erfarenhetens tydlighet för nya och icke-specialiserade användare.", special: "Speciell / Premium", specialDesc: "Tilldelad för framstående användare eller med avancerad användning och kvalitativ feedback.", total: "Totalt antal provplatser: 50" },
  plans: {
    title: "Planer och funktioner", selectPlan: "Välj plan", locked: "Denna plan är låst under den nuvarande provfasen.", lockedSub: "Val- och betalningsknappar aktiveras efter att den officiella provperioden slutar.", features: "Funktioner", hidden: "Dolt i denna plan",
    insight: { name: "Insight", price: "Gratis", desc: "För nya användare som vill prova systemet och förstå det allmänna konceptet.", features: ["Allmän marknadsstatusöversikt", "16-dagarsresa", "Dag 16-enkät", "FAQ, säkerhet och integritet", "Tydligt juridiskt meddelande"], hidden: ["Detaljerad TDL", "Detaljerad NMP", "NMP Golden Alignment", "Black Layer", "API / Webhooks", "Administrationspanel"] },
    nmpPro: { name: "NMP Pro", price: "$49", desc: "För seriösa användare som vill ha djupare förståelse för kontext, likviditet och anpassning.", features: ["TDL — Temporal dimensionslogik", "NMP — Nawaf mötespunkt", "NMP Golden Alignment", "Tydligare tolkningsrapporter", "Risknivåer och bredare kontext", "Fullständig 16-dagars provperiod"], hidden: ["Fullständigt Black Layer", "Fem skyddade suveräna lager", "API / Webhooks", "Administratörsbehörigheter", "Rå logik"] },
    elite16: { name: "Elite 16", price: "$149", desc: "För avancerade användare som vill ha den bredaste analytiska upplevelsen inom systemet.", features: ["Bredare tillgång till 16-lagers logik", "Black Layer — Djävulens advokat", "Utökad förklarbarhet", "Avancerad riskanalys och kontext", "Prioritet på rabatter och erbjudanden", "Prioritet på systemuppdateringar"], hidden: ["Fem suveräna lager skyddade i UI", "Rå logik", "Administratörsbehörigheter", "Institutionella API-nycklar"] },
    saas: { name: "NDSP SaaS", price: "Anpassad", desc: "För företag och enheter som behöver integrera NDSP i sina system.", features: ["Institutionella API-nycklar", "Webhooks för rena allmänna signaler", "Anpassade hastighetsgränser", "Granskningsloggar", "Integration med interna system", "Teknisk support och driftsgranskning"], hidden: ["Råa algoritmer", "Fullständigt skyddade lager", "Interna viktningshemligheter", "Systemegarebehörigheter"] },
  },
  trial: { badge: "NDSP Elite Trial • Begränsad institutionell provperiod", title: "Välkommen till NDSP:s 16-dagars provperiod", subtitle: "Denna fas är ägnad åt att testa plattformen före den betalda lanseringen.", duration: "Provperiodens längd", durationVal: "16 dagar från aktiveringsdatumet för provkontot.", currentPlan: "Nuvarande plan", currentPlanVal: "Trial Plan — organiserad provåtkomst före den betalda lanseringen.", benefits: "Provperiodens fördelar", benefitsVal: "Grundläggande åtkomst, definierade tillgångar och förenklat utflöde utan att avslöja intern logik.", survey: "Enkät vid periodens slut", surveyVal: "Enkät krävs för att utvärdera upplevelsen och förbättra plattformen innan expansion.", limitedSeats: "Begränsade platser", limitedSeatsVal: "Provplatser är begränsade och föremål för granskning och administrativ aktivering.", payment: "Nuvarande betalning", paymentVal: "Betalning är tillfälligt låst tills provfasen är slutförd.", start: "Förstått, starta provperiod", close: "Stäng" },
  about: { title: "Vad är NDSP? Och vad erbjuder det inte?", subtitle: "Denna plattform är utformad för att klargöra tjänstegränserna innan provperioden börjar.", whatIs: "Vad är NDSP?", whatIsItems: ["En plattform för beslutsstöd och kontextuell analys för marknader.", "Hjälper till att förstå kontext och utvärdera scenarier.", "Presenterar styrda och förenklade analytiska utdata.", "Stöder Elite 16-dagars provperiod före den betalda lanseringen."], whatNot: "Vad erbjuder NDSP INTE?", whatNotItems: ["Inte en finansiell rådgivare.", "Ger inga köp- eller säljrekommendationer.", "Utför inga transaktioner eller förvaltar kapital.", "Garanterar inte resultat eller noggrannhet av framtida scenarier."] },
  footer: { disclaimer: "Varning: NDSP är en plattform för beslutsstöd och kontextuell analys. Den ger inga finansiella rekommendationer, utför inga order och förvaltar inget användarkapital.", rights: "Alla rättigheter förbehållna" },
  languageSwitcher: { label: "Språk", search: "Sök språk...", noResults: "Inga resultat" },
};
