export default {
  nav: { home: "Nyumbani", plans: "Mipango", trial: "Majaribio", faq: "Maswali Yanayoulizwa Mara kwa Mara", login: "Ingia", register: "Jisajili" },
  hero: { badge: "NDSP Elite Trial • Majaribio ya Taasisi Yaliyopunguzwa", title: "NDSP — Jukwaa la Msaada wa Maamuzi ya Taasisi", subtitle: "Elewa muktadha wa soko • Tathmini hali • Fanya maamuzi yenye taarifa zaidi", disclaimer: "Si mapendekezo ya biashara — zana ya uchambuzi wa elimu inayosimamiwa", description: "Jukwaa salama la msaada wa maamuzi ambalo halitoi mapendekezo ya fedha ya moja kwa moja, bali linawasilisha muktadha wa uchanganuzi, hali ya hatari, ubora wa uamuzi na mwanga uliopangwa.", startTrial: "Anza Majaribio", viewJourney: "Ona Safari ya Siku 16" },
  warning: { text: "Onyo: NDSP ni jukwaa la msaada wa maamuzi na uchambuzi wa muktadha. Hajtoi mapendekezo ya fedha, hatekelezi amri, na haisimamii mtaji wa watumiaji." },
  status: { title: "Hali ya Jukwaa", visitor: "Mgeni", visitorDesc: "Jisajili kuanza majaribio yako ya siku 16.", backend: "Imeunganishwa kupitia /api", backendDesc: "Usajili, kuingia na uchunguzi vimeunganishwa na PostgreSQL.", contact: "ndsp.app@gmail.com", contactDesc: "Barua pepe rasmi kwa maswali na msaada." },
  welcome: { title: "Ujumbe wa Karibu", text: "Kwa sababu ya kujitolea kwetu kwa kuridhika kwako na kukupa fursa ya haki ya kupitia nguvu ya mfumo, tunakupa majaribio ya utangulizi wa siku 16 kukujulisha NDSP hatua kwa hatua kabla ya kujitolea yoyote.", startTrial: "Anza Majaribio", viewJourney: "Ona Safari ya Siku 16" },
  seats: { title: "Viti Vichache vya Majaribio ya NDSP", subtitle: "Viti vya majaribio vimegawanywa kuhakikisha ubora wa tathmini na utofauti wa maoni kabla ya uzinduzi wa kulipa.", specialist: "Mtaalamu / Mwanasheria", specialistDesc: "Iliyotengwa kwa wakaguzi wenye uzoefu, wataalamu na wanaovutiwa na tathmini ya kimfumo.", regular: "Mtumiaji wa Kawaida / Mpya", regularDesc: "Iliyotengwa kujaribu uwazi wa uzoefu kwa watumiaji wapya na wasio wataalamu.", special: "Maalum / Premium", specialDesc: "Iliyotengwa kwa watumiaji bora au wenye matumizi ya hali ya juu na maoni ya ubora.", total: "Jumla ya viti vya majaribio: 50 viti" },
  plans: {
    title: "Mipango na Vipengele", selectPlan: "Chagua Mpango", locked: "Mpango huu umefungwa wakati wa awamu ya majaribio ya sasa.", lockedSub: "Vifungo vya kuchagua na kulipa vitaamilishwa baada ya kipindi rasmi cha majaribio kumalizika.", features: "Vipengele", hidden: "Imefichwa katika mpango huu",
    insight: { name: "Insight", price: "Bila Malipo", desc: "Kwa watumiaji wapya wanaotaka kujaribu mfumo na kuelewa dhana ya jumla.", features: ["Muhtasari wa jumla wa hali ya soko", "Safari ya siku 16", "Uchunguzi wa siku ya 16", "Maswali Yanayoulizwa Mara kwa Mara, usalama na faragha", "Arifa wazi ya kisheria"], hidden: ["TDL ya kina", "NMP ya kina", "NMP Golden Alignment", "Black Layer", "API / Webhooks", "Paneli ya msimamizi"] },
    nmpPro: { name: "NMP Pro", price: "$49", desc: "Kwa watumiaji wanaojali wanaotaka uelewa wa kina zaidi wa muktadha, ukwasi na usanidi.", features: ["TDL — Mantiki ya Muda wa Kipimo", "NMP — Nukta ya Mkutano wa Nawaf", "NMP Golden Alignment", "Ripoti za tafsiri wazi zaidi", "Viwango vya hatari na muktadha mpana zaidi", "Majaribio kamili ya siku 16"], hidden: ["Black Layer kamili", "Tabaka tano za msingi zilindwa", "API / Webhooks", "Ruhusa za msimamizi", "Mantiki ghafi"] },
    elite16: { name: "Elite 16", price: "$149", desc: "Kwa watumiaji wa hali ya juu wanaotaka uzoefu mpana zaidi wa uchanganuzi ndani ya mfumo.", features: ["Ufikiaji mpana zaidi wa mantiki ya tabaka 16", "Black Layer — Mtetezi wa Shetani", "Uelezaji wa upanuzi", "Uchambuzi wa hatari wa hali ya juu na muktadha", "Kipaumbele katika punguzo na ofa", "Kipaumbele katika masasisho ya mfumo"], hidden: ["Tabaka tano za msingi zilindwa katika UI", "Mantiki ghafi", "Ruhusa za msimamizi", "Funguo za API za taasisi"] },
    saas: { name: "NDSP SaaS", price: "Maalum", desc: "Kwa makampuni na vyombo vinavyohitaji kuunganisha NDSP katika mifumo yao.", features: ["Funguo za API za taasisi", "Webhooks kwa mawimbi ya jumla safi", "Mipaka ya kiwango iliyobinafsishwa", "Kumbukumbu za ukaguzi", "Uunganishaji na mifumo ya ndani", "Msaada wa kiufundi na ukaguzi wa uendeshaji"], hidden: ["Algoritimu ghafi", "Tabaka zilizolindwa kikamilifu", "Siri za uzito wa ndani", "Ruhusa za mmiliki wa mfumo"] },
  },
  trial: { badge: "NDSP Elite Trial • Majaribio ya Taasisi Yaliyopunguzwa", title: "Karibu katika Majaribio ya NDSP ya Siku 16", subtitle: "Awamu hii imejitolea kujaribu jukwaa kabla ya uzinduzi wa kulipa.", duration: "Muda wa Majaribio", durationVal: "Siku 16 tangu tarehe ya uanzishaji wa akaunti ya majaribio.", currentPlan: "Mpango wa Sasa", currentPlanVal: "Trial Plan — ufikiaji wa majaribio uliopangwa kabla ya uzinduzi wa kulipa.", benefits: "Faida za Majaribio", benefitsVal: "Ufikiaji wa msingi, mali zilizofafanuliwa na matokeo yaliyorahisishwa bila kufichua mantiki ya ndani.", survey: "Uchunguzi wa Mwisho wa Kipindi", surveyVal: "Uchunguzi unahitajika ili kutathmini uzoefu na kuboresha jukwaa kabla ya upanuzi.", limitedSeats: "Viti Vichache", limitedSeatsVal: "Viti vya majaribio ni vichache na vinakabiliwa na ukaguzi na uanzishaji wa utawala.", payment: "Malipo ya Sasa", paymentVal: "Malipo yamefungwa kwa muda hadi awamu ya majaribio ikamilike.", start: "Nimeelewa, Anza Majaribio", close: "Funga" },
  about: { title: "NDSP ni nini? Na haitoi nini?", subtitle: "Jukwaa hili limeundwa kufafanua mipaka ya huduma kabla ya kuanza majaribio.", whatIs: "NDSP ni nini?", whatIsItems: ["Jukwaa la msaada wa maamuzi na uchambuzi wa muktadha kwa masoko.", "Husaidia kuelewa muktadha na kutathmini hali.", "Inawasilisha matokeo ya uchanganuzi yanayosimamiwa na kurahisishwa.", "Inasaidia majaribio ya Elite ya siku 16 kabla ya uzinduzi wa kulipa."], whatNot: "NDSP HAITOI nini?", whatNotItems: ["Si mshauri wa fedha.", "Haitoi mapendekezo ya kununua au kuuza.", "Haitekelezi miamala au kusimamia mtaji.", "Haihakikishi matokeo au usahihi wa hali za baadaye."] },
  footer: { disclaimer: "Onyo: NDSP ni jukwaa la msaada wa maamuzi na uchambuzi wa muktadha. Hajtoi mapendekezo ya fedha, hatekelezi amri, na haisimamii mtaji wa watumiaji.", rights: "Haki zote zimehifadhiwa" },
  languageSwitcher: { label: "Lugha", search: "Tafuta lugha...", noResults: "Hakuna matokeo" },
};
