export default {
  nav: { home: "Trang chủ", plans: "Gói", trial: "Dùng thử", faq: "Câu hỏi thường gặp", login: "Đăng nhập", register: "Đăng ký" },
  hero: { badge: "NDSP Elite Trial • Dùng thử tổ chức giới hạn", title: "NDSP — Nền tảng hỗ trợ quyết định tổ chức", subtitle: "Hiểu bối cảnh thị trường • Đánh giá các kịch bản • Đưa ra quyết định sáng suốt hơn", disclaimer: "Không phải khuyến nghị giao dịch — công cụ phân tích giáo dục được quản lý", description: "Nền tảng hỗ trợ quyết định an toàn không đưa ra khuyến nghị tài chính trực tiếp mà trình bày bối cảnh phân tích, trạng thái rủi ro, chất lượng quyết định và cái nhìn có tổ chức.", startTrial: "Bắt đầu dùng thử", viewJourney: "Xem hành trình 16 ngày" },
  warning: { text: "Cảnh báo: NDSP là nền tảng hỗ trợ quyết định và phân tích theo ngữ cảnh. Không đưa ra khuyến nghị tài chính, không thực hiện lệnh và không quản lý vốn người dùng." },
  status: { title: "Trạng thái nền tảng", visitor: "Khách", visitorDesc: "Đăng ký để bắt đầu dùng thử 16 ngày.", backend: "Kết nối qua /api", backendDesc: "Đăng ký, đăng nhập và khảo sát kết nối với PostgreSQL.", contact: "ndsp.app@gmail.com", contactDesc: "Email chính thức cho các yêu cầu và hỗ trợ." },
  welcome: { title: "Thông điệp chào mừng", text: "Vì cam kết với sự hài lòng của bạn và để trao cho bạn cơ hội công bằng để trải nghiệm sức mạnh của hệ thống, chúng tôi cung cấp cho bạn 16 ngày dùng thử giới thiệu để làm quen dần với NDSP trước bất kỳ cam kết nào.", startTrial: "Bắt đầu dùng thử", viewJourney: "Xem hành trình 16 ngày" },
  seats: { title: "Chỗ dùng thử NDSP giới hạn", subtitle: "Các chỗ dùng thử đã được phân bổ để đảm bảo chất lượng đánh giá và sự đa dạng phản hồi trước khi ra mắt trả phí.", specialist: "Chuyên gia / Học thuật", specialistDesc: "Dành cho các nhà đánh giá có kinh nghiệm, chuyên gia và những người quan tâm đến đánh giá hệ thống.", regular: "Người dùng thông thường / Mới bắt đầu", regularDesc: "Dành để kiểm tra sự rõ ràng của trải nghiệm cho người dùng mới và không chuyên.", special: "Đặc biệt / Cao cấp", specialDesc: "Dành cho người dùng xuất sắc hoặc có mức sử dụng nâng cao và phản hồi định tính.", total: "Tổng số chỗ dùng thử: 50 chỗ" },
  plans: {
    title: "Gói và tính năng", selectPlan: "Chọn gói", locked: "Gói này bị khóa trong giai đoạn dùng thử hiện tại.", lockedSub: "Nút chọn và thanh toán sẽ được kích hoạt sau khi giai đoạn dùng thử chính thức kết thúc.", features: "Tính năng", hidden: "Ẩn trong gói này",
    insight: { name: "Insight", price: "Miễn phí", desc: "Cho người dùng mới muốn trải nghiệm hệ thống và hiểu khái niệm chung.", features: ["Tổng quan chung về trạng thái thị trường", "Hành trình 16 ngày", "Khảo sát ngày 16", "Câu hỏi thường gặp, bảo mật và quyền riêng tư", "Thông báo pháp lý rõ ràng"], hidden: ["TDL chi tiết", "NMP chi tiết", "NMP Golden Alignment", "Black Layer", "API / Webhooks", "Bảng điều khiển quản trị"] },
    nmpPro: { name: "NMP Pro", price: "$49", desc: "Cho người dùng nghiêm túc muốn hiểu sâu hơn về bối cảnh, thanh khoản và sự liên kết.", features: ["TDL — Logic Chiều Thời Gian", "NMP — Điểm Gặp Gỡ Nawaf", "NMP Golden Alignment", "Báo cáo giải thích rõ ràng hơn", "Mức độ rủi ro và bối cảnh rộng hơn", "Dùng thử đầy đủ 16 ngày"], hidden: ["Black Layer đầy đủ", "Năm lớp chủ quyền được bảo vệ", "API / Webhooks", "Quyền quản trị", "Logic thô"] },
    elite16: { name: "Elite 16", price: "$149", desc: "Cho người dùng nâng cao muốn trải nghiệm phân tích rộng nhất trong hệ thống.", features: ["Truy cập rộng hơn vào logic 16 lớp", "Black Layer — Luật sư Quỷ", "Khả năng giải thích mở rộng", "Phân tích rủi ro nâng cao và bối cảnh", "Ưu tiên giảm giá và ưu đãi", "Ưu tiên cập nhật hệ thống"], hidden: ["Năm lớp chủ quyền được bảo vệ trong UI", "Logic thô", "Quyền quản trị", "Khóa API tổ chức"] },
    saas: { name: "NDSP SaaS", price: "Tùy chỉnh", desc: "Cho các công ty và tổ chức cần tích hợp NDSP vào hệ thống của họ.", features: ["Khóa API tổ chức", "Webhooks cho tín hiệu chung sạch", "Giới hạn tốc độ tùy chỉnh", "Nhật ký kiểm toán", "Tích hợp với hệ thống nội bộ", "Hỗ trợ kỹ thuật và đánh giá vận hành"], hidden: ["Thuật toán thô", "Các lớp được bảo vệ hoàn toàn", "Bí mật trọng số nội bộ", "Quyền chủ sở hữu hệ thống"] },
  },
  trial: { badge: "NDSP Elite Trial • Dùng thử tổ chức giới hạn", title: "Chào mừng đến với dùng thử NDSP 16 ngày", subtitle: "Giai đoạn này dành riêng cho việc thử nghiệm nền tảng trước khi ra mắt trả phí.", duration: "Thời gian dùng thử", durationVal: "16 ngày kể từ ngày kích hoạt tài khoản dùng thử.", currentPlan: "Gói hiện tại", currentPlanVal: "Trial Plan — truy cập dùng thử có tổ chức trước khi ra mắt trả phí.", benefits: "Lợi ích dùng thử", benefitsVal: "Truy cập cơ bản, tài sản xác định và đầu ra đơn giản hóa mà không tiết lộ logic nội bộ.", survey: "Khảo sát cuối kỳ", surveyVal: "Cần khảo sát để đánh giá trải nghiệm và cải thiện nền tảng trước khi mở rộng.", limitedSeats: "Chỗ giới hạn", limitedSeatsVal: "Chỗ dùng thử giới hạn và phải được xem xét và kích hoạt bởi quản trị viên.", payment: "Thanh toán hiện tại", paymentVal: "Thanh toán tạm thời bị khóa cho đến khi giai đoạn dùng thử hoàn tất.", start: "Đã hiểu, bắt đầu dùng thử", close: "Đóng" },
  about: { title: "NDSP là gì? Và nó không cung cấp gì?", subtitle: "Nền tảng này được thiết kế để làm rõ giới hạn dịch vụ trước khi bắt đầu dùng thử.", whatIs: "NDSP là gì?", whatIsItems: ["Nền tảng hỗ trợ quyết định và phân tích theo ngữ cảnh cho thị trường.", "Giúp hiểu bối cảnh và đánh giá các kịch bản.", "Trình bày đầu ra phân tích được quản lý và đơn giản hóa.", "Hỗ trợ dùng thử Elite 16 ngày trước khi ra mắt trả phí."], whatNot: "NDSP KHÔNG cung cấp gì?", whatNotItems: ["Không phải cố vấn tài chính.", "Không đưa ra khuyến nghị mua hoặc bán.", "Không thực hiện giao dịch hoặc quản lý vốn.", "Không đảm bảo kết quả hoặc độ chính xác của các kịch bản tương lai."] },
  footer: { disclaimer: "Cảnh báo: NDSP là nền tảng hỗ trợ quyết định và phân tích theo ngữ cảnh. Không đưa ra khuyến nghị tài chính, không thực hiện lệnh và không quản lý vốn người dùng.", rights: "Bảo lưu mọi quyền" },
  languageSwitcher: { label: "Ngôn ngữ", search: "Tìm kiếm ngôn ngữ...", noResults: "Không có kết quả" },
};
